port: 7788
prefix: api

openapi:
  enabled: true
  path: /openapi
  title: XDD SPACE API
  description: XDD SPACE API documentation
  version: 1.0.0

logger:
  level: info
  filePath: # logs/app.log 留空则不启用文件日志
